frameStarter:
    path: /extern
    defaults:
        _controller: Chuckki\HvzIframeBundle\Controller\FrameController:loadFrameAction
        _scope: frontend
        _token_check: true
    methods: [GET]

formProceed:
    path: /extern
    defaults:
        _controller: Chuckki\HvzIframeBundle\Controller\FrameController:checkFormAction
        _scope: frontend
        _token_check: true
    methods: [POST]

hvzPrice:
    path: /extern/getprice/{id}
    defaults:
        _controller: Chuckki\HvzIframeBundle\Controller\FrameController:getHvbPrice
        _scope: frontend
        _token_check: true
    methods: [POST]

hvzContent:
    path: /extern/hvb/{id}
    defaults:
        _controller: Chuckki\HvzIframeBundle\Controller\FrameController:getHvbInfo
        _scope: frontend
        _token_check: false
