frameStarter:
    path: /extern/{customer}/
    defaults:
        _controller: Chuckki\HvzIframeBundle\Controller\FrameController:loadFrameAction
        _scope: frontend
        _token_check: true
    methods: [GET]

formProceed:
    path: /extern/{customer}/submit/{id}
    defaults:
        _controller: Chuckki\HvzIframeBundle\Controller\FrameController:checkFormAction
        _scope: frontend
        _token_check: true
    methods: [POST]

hvzPrice:
    path: /extern/{customer}/getprice/{id}
    defaults:
        _controller: Chuckki\HvzIframeBundle\Controller\FrameController:getHvbPrice
        _scope: frontend
        _token_check: true
    methods: [POST]

hvzContent:
    path: /extern/{customer}/hvb/{id}/
    defaults:
        _controller: Chuckki\HvzIframeBundle\Controller\FrameController:getHvbInfo
        _scope: frontend
        _token_check: false


hvzFramePages:
    path: /extern/{customer}/page/{alias}/
    defaults:
        _controller: Chuckki\HvzIframeBundle\Controller\FramePages:showPageInFrameAction
        _scope: frontend
        _token_check: false
