services:
    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - ["setContainer", ["@service_container"]]

    Chuckki\HvzIframeBundle\Controller\FrameController:
        arguments:
            - '%kernel.project_dir%'
            - "@session"
            - "@contao.framework"
            - "@hvz.auth"
            - "@hvz.communicator"
        tags: ['controller.service_arguments']


    Chuckki\HvzIframeBundle\Controller\FramePages:
        arguments:
            - '%kernel.project_dir%'
            - "@session"
            - "@contao.framework"
        tags: ['controller.service_arguments']

    hvz.auth:
        class: Chuckki\HvzIframeBundle\Services\Authenticator
        autowire: true

    hvz.communicator:
        class: Chuckki\HvzIframeBundle\Services\Communicator
        arguments:
            - '@hvz.auth'
            - '@swiftmailer.mailer.default'
            - '@twig'
            - '@monolog.logger'
            - '@hvz.order.manager'

    hvz.order.manager:
        class: Chuckki\HvzIframeBundle\Services\OrderManager
        arguments:
            - '@monolog.logger'
