services:
    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - ["setContainer", ["@service_container"]]

    Chuckki\HvzIframeBundle\Controller\FrameController:
        arguments:
            - '%kernel.project_dir%'
            - "@session"
            - "@contao.framework"
            - "@hvz.auth"
        tags: ['controller.service_arguments']


    Chuckki\HvzIframeBundle\Controller\FramePages:
        arguments:
            - '%kernel.project_dir%'
            - "@session"
            - "@contao.framework"
        tags: ['controller.service_arguments']

    hvz.auth:
        class: Chuckki\HvzIframeBundle\Services\Authenticator
        arguments:
            - '%iframe_user%'

    Chuckki\HvzIframeBundle\Services\Authenticator:
        arguments:
            - '%iframe_user%'
